export const DISPLAY_ALERT = "SHOW_ALERT";

export const CLEAR_ALERT = "CLEAR_ALERT";

export const RGISTER_USER_BEGIN = "RGISTER_USER_BEGIN";
export const RGISTER_USER_SUCCESS = "RGISTER_USER_SUCCESS";
export const RGISTER_USER_ERROR = "RGISTER_USER_ERROR";
